apiVersion: apps/v1
kind: Deployment
metadata: 
 name: order
 namespace: nagp
 labels:
  app: order
spec:
 replicas: 1
 selector:
  matchLabels:
   app: orderservice
 template:
  metadata:
   labels:
    app: orderservice
  spec:
   containers:
   - name: order
     image: girishsuri/order:2
     ports:
     - containerPort: 3000
     volumeMounts:
      - name: order
        mountPath: /mnt
   volumes:
   - name: order
     configMap:
      name: orderdata